packages:
  - "packages/*"

allowBuilds:
  "@parcel/watcher": true
  core-js: false
  esbuild: true
  msgpackr-extract: false
  msw: true
  sharp: true
  workerd: true

minimumReleaseAge: 10080 # 7 days
trustPolicy: no-downgrade
